<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Test3" duration-ms="57254" started-at="2017-05-18T18:37:15Z" finished-at="2017-05-18T18:38:12Z">
    <groups>
      <group name="Secondary">
        <method signature="HPETest.TC_134_ValidateErrorMessageForWrongUsername()[pri:0, instance:Regression_Utilities.HPETest@6ea12c19]" name="TC_134_ValidateErrorMessageForWrongUsername" class="Regression_Utilities.HPETest"/>
      </group> <!-- Secondary -->
      <group name="Primary">
        <method signature="HPETest.TC_134_ValidateErrorMessageForWrongUsername()[pri:0, instance:Regression_Utilities.HPETest@6ea12c19]" name="TC_134_ValidateErrorMessageForWrongUsername" class="Regression_Utilities.HPETest"/>
      </group> <!-- Primary -->
    </groups>
    <test name="HPETest" duration-ms="57254" started-at="2017-05-18T18:37:15Z" finished-at="2017-05-18T18:38:12Z">
      <class name="Regression_Utilities.HPETest">
        <test-method status="PASS" signature="loadDevice()[pri:0, instance:Regression_Utilities.HPETest@6ea12c19]" name="loadDevice" is-config="true" duration-ms="41917" started-at="2017-05-19T00:06:33Z" finished-at="2017-05-19T00:07:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadDevice -->
        <test-method status="FAIL" signature="TC_134_ValidateErrorMessageForWrongUsername()[pri:0, instance:Regression_Utilities.HPETest@6ea12c19]" name="TC_134_ValidateErrorMessageForWrongUsername" duration-ms="57201" started-at="2017-05-19T00:07:15Z" finished-at="2017-05-19T00:08:12Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Element with by xpath 'xpath|(//*[@label="Address"])[2]			' wasn't found.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'BDC8-LX-5111KRH', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Element with by xpath 'xpath|(//*[@label="Address"])[2]			' wasn't found.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'BDC8-LX-5111KRH', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at com.perfectomobile.selenium.MobileApplication.getSingleElement(MobileApplication.java:369)
	at com.perfectomobile.selenium.MobileApplication.findElementByXPath(MobileApplication.java:211)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at com.perfectomobile.selenium.MobileApplication.findElement(MobileApplication.java:150)
	at Libraries.HPEOperations.EnterURL(HPEOperations.java:221)
	at Libraries.HPEOperations.Install_App_HPE_GO_iphone7and6S(HPEOperations.java:333)
	at Libraries.HPEOperations.Install_App_HPE_GO_iOS(HPEOperations.java:367)
	at Libraries.HPECommonFunctions.Open_App_HPE_iOS(HPECommonFunctions.java:148)
	at Libraries.HPECommonFunctions.Open_App_HPE(HPECommonFunctions.java:126)
	at Regression_Utilities.HPETest.TC_134_ValidateErrorMessageForWrongUsername(HPETest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_134_ValidateErrorMessageForWrongUsername -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:Regression_Utilities.HPETest@6ea12c19]" name="afterSuite" is-config="true" duration-ms="1" started-at="2017-05-19T00:08:12Z" finished-at="2017-05-19T00:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- Regression_Utilities.HPETest -->
    </test> <!-- HPETest -->
  </suite> <!-- Test3 -->
</testng-results>
